[project]
name = "lecture-02-pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ratanon-Thongseekaew", email = "ratanon_thongseekaew@hotmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "asteval>=1.0.9",
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
lecture-02-pytest = "lecture_02_pytest:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx2>=2.10.0",
    "pytest>=9.1.1",
]
